import {
  Activity,
  BedDouble,
  BookOpen,
  Braces,
  Brain,
  Calculator,
  Calendar,
  Car,
  CheckSquare,
  ClipboardList,
  Cloud,
  CloudSun,
  Code,
  CreditCard,
  Database,
  FileText,
  FolderOpen,
  GraduationCap,
  HeartPulse,
  ImageIcon,
  Languages,
  Link2,
  ListChecks,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Newspaper,
  PenTool,
  Percent,
  Phone,
  Plane,
  Play,
  Presentation,
  Receipt,
  Rocket,
  ScanEye,
  ScanLine,
  ShoppingBag,
  Sparkles,
  StickyNote,
  Store,
  Table,
  TrendingUp,
  Truck,
  Users,
  Video,
  Wallet,
} from "lucide-react";

export const products = [
  { slug: "briefly", name: "Briefly", sub: "Summarize fast", tagline: "Long docs, made clear.", description: "Turn documents, meeting notes, and product updates into crisp summaries your team can scan in minutes.", icon: FileText, tile: "from-zinc-500 to-zinc-800" },
  { slug: "chat", name: "Chat", sub: "Message anyone", tagline: "Conversations that keep up.", description: "Instant messaging for people and teams with threads, reactions, and calls in your browser.", icon: MessageCircle, tile: "from-sky-400 to-blue-600" },
  { slug: "mail", name: "Mail", sub: "Email, organized", tagline: "The inbox, finally calm.", description: "Fast, organized email that sorts itself so you only see what matters.", icon: Mail, tile: "from-blue-500 to-indigo-600" },
  { slug: "meet", name: "Meet", sub: "Video calls", tagline: "Meetings without the friction.", description: "One link, clear video, and notes that help everyone leave with the same next step.", icon: Video, tile: "from-indigo-400 to-violet-600" },
  { slug: "voice", name: "Voice", sub: "Cloud calling", tagline: "Your phone line, in the cloud.", description: "Calls, voicemail, and a business number that works on every device.", icon: Phone, tile: "from-cyan-400 to-sky-600" },
  { slug: "teams", name: "Teams", sub: "Work together", tagline: "One space for the whole company.", description: "Channels, people, and projects connected so nothing gets lost.", icon: Users, tile: "from-blue-400 to-cyan-600" },
  { slug: "docs", name: "Docs", sub: "Write together", tagline: "Write together, in real time.", description: "Documents built for collaboration with comments, history, and instant sharing.", icon: FileText, tile: "from-violet-400 to-purple-600" },
  { slug: "notes", name: "Notes", sub: "Capture ideas", tagline: "Ideas, the moment they arrive.", description: "Capture anything in a tap and find it again in seconds.", icon: StickyNote, tile: "from-amber-400 to-orange-500" },
  { slug: "tasks", name: "Tasks", sub: "Plan and do", tagline: "Plan the day. Ship the week.", description: "Simple lists and boards that keep you and your team moving.", icon: CheckSquare, tile: "from-emerald-400 to-green-600" },
  { slug: "calendar", name: "Calendar", sub: "Your schedule", tagline: "It's time.", description: "All of your commitments in one beautifully designed calendar for work and life.", icon: Calendar, tile: "from-rose-400 to-red-500" },
  { slug: "sheets", name: "Sheets", sub: "Smart spreadsheets", tagline: "Spreadsheets that think with you.", description: "Formulas, charts, and automation without the learning curve.", icon: Table, tile: "from-green-400 to-emerald-600" },
  { slug: "forms", name: "Forms", sub: "Collect answers", tagline: "Collect answers, not headaches.", description: "Beautiful forms and surveys with results that organize themselves.", icon: ClipboardList, tile: "from-purple-400 to-fuchsia-600" },
  { slug: "slides", name: "Slides", sub: "Beautiful decks", tagline: "Presentations people remember.", description: "Design-quality decks in minutes, with live collaboration built in.", icon: Presentation, tile: "from-orange-400 to-amber-600" },
  { slug: "travel", name: "Travel", sub: "Plan trips", tagline: "The whole trip, one place.", description: "Flights, plans, and itineraries that update themselves as things change.", icon: Plane, tile: "from-sky-400 to-cyan-600" },
  { slug: "stay", name: "Stay", sub: "Book stays", tagline: "The right place to sleep.", description: "Compare stays, read what matters, and book in a few taps.", icon: BedDouble, tile: "from-teal-400 to-emerald-600" },
  { slug: "maps", name: "Maps", sub: "Go anywhere", tagline: "Get anywhere with confidence.", description: "Live navigation, transit, and places, fast and beautifully clear.", icon: Map, tile: "from-green-400 to-teal-600" },
  { slug: "rides", name: "Rides", sub: "Get a ride", tagline: "A car when you need one.", description: "Request a ride in seconds with upfront pricing and live tracking.", icon: Car, tile: "from-zinc-500 to-zinc-700" },
  { slug: "pay", name: "Pay", sub: "Send money", tagline: "Money moves instantly.", description: "Send, receive, and split payments with anyone from one account.", icon: CreditCard, tile: "from-emerald-400 to-teal-600" },
  { slug: "wallet", name: "Wallet", sub: "Cards and passes", tagline: "Everything valuable, together.", description: "Cards, passes, and balances secured in one place on every device.", icon: Wallet, tile: "from-lime-400 to-green-600" },
  { slug: "invoice", name: "Invoice", sub: "Bill clients", tagline: "Bill clients in a minute.", description: "Professional invoices, automatic reminders, and faster payments.", icon: Receipt, tile: "from-teal-400 to-cyan-600" },
  { slug: "books", name: "Books", sub: "Easy accounting", tagline: "Accounting, minus the pain.", description: "Bookkeeping for small business that reconciles itself.", icon: Calculator, tile: "from-cyan-500 to-blue-600" },
  { slug: "tax", name: "Tax", sub: "File taxes", tagline: "File without the fear.", description: "Guided filing that checks the details and keeps the process simple.", icon: Percent, tile: "from-green-500 to-emerald-700" },
  { slug: "photos", name: "Photos", sub: "Every memory", tagline: "Every memory, safe and searchable.", description: "Storage with search that understands what is in the picture.", icon: ImageIcon, tile: "from-pink-400 to-rose-600" },
  { slug: "music", name: "Music", sub: "Millions of songs", tagline: "Millions of songs. Zero clutter.", description: "A listening experience built around you, not noisy playlists.", icon: Music, tile: "from-fuchsia-400 to-pink-600" },
  { slug: "stream", name: "Stream", sub: "Watch anywhere", tagline: "Watch what you love, anywhere.", description: "Films and series in beautiful quality on every screen you own.", icon: Play, tile: "from-red-400 to-rose-600" },
  { slug: "podcasts", name: "Podcasts", sub: "Listen daily", tagline: "Voices worth your commute.", description: "Discover, follow, and pick up exactly where you left off.", icon: Mic, tile: "from-purple-400 to-violet-600" },
  { slug: "news", name: "News", sub: "Curated stories", tagline: "The stories that matter.", description: "Curated journalism from trusted sources, free of the noise.", icon: Newspaper, tile: "from-slate-500 to-slate-700" },
  { slug: "code", name: "Code", sub: "Code in flow", tagline: "An editor built for flow.", description: "Fast, intelligent, and collaborative coding in the browser.", icon: Code, tile: "from-indigo-400 to-blue-600" },
  { slug: "cloud", name: "Cloud", sub: "Instant infrastructure", tagline: "Infrastructure that scales itself.", description: "Compute, storage, and networking that grow with your traffic.", icon: Cloud, tile: "from-sky-400 to-indigo-600" },
  { slug: "api", name: "API", sub: "Platform API", tagline: "Build on Lnkbase.", description: "One platform API for every Lnkbase product, with keys in minutes.", icon: Braces, tile: "from-violet-500 to-indigo-700" },
  { slug: "deploy", name: "Deploy", sub: "Ship instantly", tagline: "Ship to production in seconds.", description: "Push your code and Lnkbase handles builds, previews, and rollbacks.", icon: Rocket, tile: "from-orange-400 to-red-600" },
  { slug: "data", name: "Data", sub: "Serverless databases", tagline: "Databases without the ops.", description: "Serverless Postgres and analytics that stay fast.", icon: Database, tile: "from-cyan-400 to-blue-700" },
  { slug: "monitor", name: "Monitor", sub: "Live monitoring", tagline: "Know before your users do.", description: "Uptime, errors, and performance in one live dashboard.", icon: Activity, tile: "from-rose-400 to-pink-600" },
  { slug: "assist", name: "Assist", sub: "AI assistant", tagline: "An AI for everything you do.", description: "Your assistant across every Lnkbase product: ask, draft, and automate.", icon: Sparkles, tile: "from-violet-400 to-fuchsia-600" },
  { slug: "translate", name: "Translate", sub: "Every language", tagline: "Speak every language.", description: "Instant translation for text, voice, and documents.", icon: Languages, tile: "from-blue-400 to-violet-600" },
  { slug: "vision", name: "Vision", sub: "Understand images", tagline: "Understand any image.", description: "Extract, analyze, and search the contents of images and documents.", icon: ScanEye, tile: "from-fuchsia-400 to-purple-700" },
  { slug: "write", name: "Write", sub: "AI writing", tagline: "From rough idea to polished draft.", description: "AI writing that keeps your voice and sharpens your point.", icon: PenTool, tile: "from-pink-400 to-fuchsia-600" },
  { slug: "shop", name: "Shop", sub: "Shop everything", tagline: "Everything you want, delivered.", description: "Shop millions of products with one cart and one checkout.", icon: ShoppingBag, tile: "from-amber-400 to-orange-600" },
  { slug: "store", name: "Store", sub: "Sell online", tagline: "Your storefront, open today.", description: "Launch an online store with payments and shipping built in.", icon: Store, tile: "from-orange-400 to-rose-500" },
  { slug: "ship", name: "Ship", sub: "Simple logistics", tagline: "Logistics made simple.", description: "Labels, tracking, and delivery updates your customers will love.", icon: Truck, tile: "from-yellow-500 to-amber-600" },
  { slug: "market", name: "Market", sub: "Sales insights", tagline: "Insights that grow sales.", description: "Real-time analytics on what sells, to whom, and why.", icon: TrendingUp, tile: "from-emerald-400 to-lime-600" },
  { slug: "fit", name: "Fit", sub: "Train smarter", tagline: "Workouts that fit your life.", description: "Training plans, tracking, and coaching that adapt to you.", icon: HeartPulse, tile: "from-red-400 to-pink-600" },
  { slug: "mind", name: "Mind", sub: "Daily calm", tagline: "A calmer head, daily.", description: "Meditation, focus sessions, and breathing exercises in minutes a day.", icon: Brain, tile: "from-teal-400 to-cyan-600" },
  { slug: "sleep", name: "Sleep", sub: "Sleep better", tagline: "Wind down. Wake up better.", description: "Sleep tracking and smart routines for genuinely restful nights.", icon: Moon, tile: "from-indigo-500 to-violet-700" },
  { slug: "learn", name: "Learn", sub: "Practical courses", tagline: "Courses from people who do the work.", description: "Practical skills taught by practitioners, at your own pace.", icon: GraduationCap, tile: "from-blue-400 to-sky-600" },
  { slug: "read", name: "Read", sub: "Books and audiobooks", tagline: "A library in your pocket.", description: "Books and audiobooks, synced across every device you own.", icon: BookOpen, tile: "from-amber-500 to-orange-700" },
  { slug: "quiz", name: "Quiz", sub: "Smart practice", tagline: "Practice that actually sticks.", description: "Spaced repetition and smart quizzes that make learning stay.", icon: ListChecks, tile: "from-lime-400 to-emerald-600" },
  { slug: "drive", name: "Drive", sub: "Files everywhere", tagline: "Your files, on every device.", description: "Store, sync, and share anything with people you trust.", icon: FolderOpen, tile: "from-yellow-400 to-amber-600" },
  { slug: "vault", name: "Vault", sub: "Passwords secured", tagline: "Locked down. Always with you.", description: "Passwords, keys, and secrets protected with end-to-end encryption.", icon: Lock, tile: "from-slate-600 to-zinc-800" },
  { slug: "scan", name: "Scan", sub: "Paper to PDF", tagline: "Paper to PDF in one tap.", description: "Crisp scans, automatic cropping, and instant text recognition.", icon: ScanLine, tile: "from-gray-500 to-slate-700" },
  { slug: "weather", name: "Weather", sub: "Local forecasts", tagline: "Forecasts you can plan around.", description: "Hyperlocal forecasts, radar, and alerts that arrive in time.", icon: CloudSun, tile: "from-sky-300 to-blue-500" },
  { slug: "links", name: "Links", sub: "Short links", tagline: "Short links. Smart redirects.", description: "Branded short links with clear analytics on every click.", icon: Link2, tile: "from-cyan-400 to-teal-600" },
] as const;

export type Product = (typeof products)[number];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
